- name: Install NDK
        run: sdkmanager "ndk;26.1.10909125"

      - name: Install dependencies
        run: npm install

      # 使用 --yes 跳过交互
      - name: Tauri Android Init
        run: npx tauri android init --yes
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/26.1.10909125

      - name: Build Android Debug
        run: npx tauri android build --debug
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/26.1.10909125